export const fonts = {
    LIGHT: 'Poppins-Light',
    MEDIUM: 'Poppins-Medium',
    Bold: 'Poppins-Bold',
    Italic: 'Poppins-Italic',
    Regular: 'Poppins-Regular',
    Thin: 'Poppins-Thin',
    ExtraBold: 'Poppins-ExtraBold',
    Bolditalic: 'Poppins-Bolditalic',
    ExtraLight: 'Poppins-ExtraLight',
    LightItalic: 'Poppins-LightItalic',
    MediumItalic: 'Poppins-MediumItalic',
    SemiBold: 'Poppins-SemiBold',
    SemiBoldItalic: 'Poppins-SemiBoldItalic',
    ThinItalic: 'Poppins-ThinItalic',
};
