export enum screens {
    Signin = 'Signin',
    Signup = 'Signup',
    Home = 'Home',
    DoctorsStack = 'DoctorsStack',
    PatientsStack = 'PatientsStack',
    Doctors = 'Doctors',
    Patients = 'Patients',
    BookAppointment = 'BookAppointment',
    ViewAppointments = 'ViewAppointments',
    AddDoctor = 'AddDoctor',
    AppointmentsArrived = 'AppointmentsArrived',
    SelectDoctor = 'SelectDoctor',
    UserDetails = 'UserDetails',
}
